blogs/urls.py
"""
URL configuration for config app.
"""

from django.urls import path

from blogs.apps import BlogsConfig
from blogs.views import (
    BlogsListView,
    BlogsDetailView,
    BlogsCreateView,
    BlogsUpdateView,
    BlogsDeleteView,
    toggle_published,
)
from django.conf.urls.static import static
from django.conf import settings

app_name = BlogsConfig.name

urlpatterns = [
    path("blogs", BlogsListView.as_view(), name="blogs_list"),
    path("<int:pk>/", BlogsDetailView.as_view(), name="blogs_detail"),
    path("create", BlogsCreateView.as_view(), name="blogs_create"),
    path("<int:pk>/update/", BlogsUpdateView.as_view(), name="blogs_update"),
    path("<int:pk>/delete/", BlogsDeleteView.as_view(), name="blogs_delete"),
    path("published/<int:pk>/", toggle_published, name="toggle_published"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="product_list")),
    path("blogs/", include("blogs.urls", namespace="blogs")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

from catalog.models import NULLABLE


class Blogs(models.Model):
    """Класс для хранения блоговой записи"""

    headline = models.CharField(
        max_length=150,
        verbose_name="Заголовок",
        help_text="Введите заголовок",
    )

    slug = models.CharField(
        max_length=150,
        verbose_name="Slug",
        help_text="Введите slug",
    )

    content = models.TextField(
        verbose_name="Содержимое",
        help_text="Введите содержимое",
        **NULLABLE,
    )

    preview = models.ImageField(
        upload_to="blogs/",
        verbose_name="Изображение (превью)",
        help_text="Добавьте превью",
        **NULLABLE,
    )

    created_at = models.DateField(auto_now_add=True, verbose_name="Дата создания")

    is_published = models.BooleanField(verbose_name="Опубликовано", default=False)

    count_views = models.IntegerField(verbose_name="Просмотров", default=0, **NULLABLE)

    def __str__(self):
        return f"{self.headline}"

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"
        permissions = [
            ("can_publish", "Can publish"),
        ]

blogs/forms.py
from django.forms import ModelForm

from blogs.models import Blogs


class ProductForm(ModelForm):
    """Форма продукта"""

    class Meta:
        model = Blogs
        exclude = (
            "created_at",
            "count_views",
        )

blogs/views.py
from audioop import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import (
    ListView,
    DeleteView,
    CreateView,
    UpdateView,
    DetailView,
)

from blogs.models import Blogs


class BlogsListView(ListView):
    """Страница списка блогов"""

    model = Blogs

    def get_queryset(self, *args, **kwargs):
        """Получает блоги, которые опубликованы"""
        queryset = super().get_queryset(*args, **kwargs)
        if self.request.GET.get("pub") == "True":
            queryset = queryset.filter(is_published=True)
            return queryset

        # все блоги
        return queryset


class BlogsDetailView(DetailView):
    """Страница просмотра блога"""

    model = Blogs

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["headline"] = Blogs.objects.get(pk=self.kwargs["pk"])
        return context_data

    def get_object(self, **kwargs):
        """Счетчик просмотров"""
        object = super().get_object(**kwargs)
        if object.count_views is None:
            object.count_views = 1
        else:
            object.count_views += 1
        object.save()

        return object


class BlogsCreateView(LoginRequiredMixin, CreateView):
    """Страница создания блога"""

    model = Blogs
    fields = ("headline", "content", "preview")
    success_url = reverse_lazy("blogs:blogs_list")

    def form_valid(self, form):
        """Проверяет данные на валидность и генерирует slug"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.headline)
            new_blog.save()
        return super().form_valid(form)


class BlogsUpdateView(LoginRequiredMixin, UpdateView):
    """Страница редактирования блога"""

    model = Blogs
    fields = ("headline", "content", "preview")
    success_url = reverse_lazy("blogs:blogs_detail")

    def form_valid(self, form):
        """Проверяет данные на валидность и генерирует slug"""
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.headline)
            new_blog.save()
        return super().form_valid(form)

    def get_success_url(self):
        """В случае успеха переходим на просмотр блога"""
        return reverse("blogs:blogs_detail", args=[self.kwargs.get("pk")])


class BlogsDeleteView(LoginRequiredMixin, DeleteView):
    """Страница удаления блока"""

    model = Blogs
    success_url = reverse_lazy("blogs:blogs_list")


@login_required
def toggle_published(request, pk):
    """Изменяет признак публикации блога"""
    blog = get_object_or_404(Blogs, pk=pk)
    if blog.is_published:
        blog.is_published = False
    else:
        blog.is_published = True

    blog.save()

    return redirect(reverse("blogs:blogs_list"))

blogs/templates/blogs/blogs_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container">
    <div class="row g-7 col-lg-8">
        <div class="container">
            <div class="row text-start">
                <div class="col-lg-9 col-md-6 col-sm-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-header">
                            Удаление блога
                        </div>
                        <div class="card-body">
                            <h4 class="card-title"> {{ object }}</h4>
                            <h6 class="card-subtitle mb-2 text-muted">slug: {{ object.slug }}</h6>
                            {% if object.is_published %}
                            <small class="blockquote-footer">Опубликовано</small>
                            {% else %}
                            <small class="blockquote-footer">Не опубликовано</small>
                            {% endif %}
                            <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                                <div class="row">
                                    <p class="card-text">Вы действительно хотите удалить блог?</p>
                                    <p class="card-text"></p>
                                </div>
                                <div class="row"></div>
                                {% csrf_token %}
                                <div class="button-group">
                                    <button type="submit" class="btn btn-primary">
                                        Удалить
                                    </button>
                                    <a class="btn btn-btn-primary" href="{% url 'blogs:blogs_list'%}" role="button">
                                        Отмена
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blogs_detail.html
{% extends 'catalog/base.html' %}

{% load my_tags %}
{% block content %}


<div class="album py-5 bg-light">
    <div class="container">

       {{ object.name }}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            {% if object.preview %}
                        <img class="card-img-top" src="{{ object.preview|media_filter }}"
                             style="max-width: 600px; max-height: 400px">
                        {% endif %}
            <div class="card-body">
              <h5 class="card-title">{{ object.name }}</h5>
              <p class="card-subtitle">{{ object.slug }}</p>
              <p class="card-text">{{ object.content }}</p>
              <p class="blockquote-footer">Просмотров: {{ object.count_views }}</p>
               <p class="blockquote-footer">Дата создания: {{ object.created_at }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a class="btn btn-primary" href="{% url 'blogs:blogs_list' %}" role="button">Назад</a>
                </div>
                {% if object.is_published %}
                  <small class="blockquote-footer">Опубликовано</small>
                {% else %}
                  <small class="blockquote-footer">Не опубликовано</small>
                {% endif %}
                <p class="card-text">{{ object.content }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

blogs/templates/blogs/blogs_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Сохранить
                            {% else %}
                            Создать
                            {% endif %}
                        </button>
                        <a class="btn btn-primary" href="{% url 'blogs:blogs_list' %}" role="button">Назад</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

blogs/templates/blogs/blogs_list.html
{% extends 'catalog/base.html' %}

{% block content %}
<main class="container">
    <div class="row">
        <div class="col-12">
            <p>
                <a href="{% url 'blogs:blogs_list' %}?pub=True" class="btn btn-primary my-2">Опубликованные
                    блоги</a>
                <a href="{% url 'blogs:blogs_list' %}?pub=False" class="btn btn-primary my-2">Все
                    блоги</a>

            </p>
        </div>
    </div>
    <div class="col-12">
        <div class="btn-group">
            {% if perms.blogs.add_blogs %}
            <a class="btn btn-primary my-2" href="{% url 'blogs:blogs_create' %}" role="button">Добавить
                новый блог</a>
            {% endif %}
        </div>
    </div>
    <div class="row mb-2">
    {% for object in object_list %}
    <div class="col-md-6">
        <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
            <div class="col p-4 d-flex flex-column position-static">
                <h3 class="mb-0">{{ object }}</h3>
                <p class="card-text">
                    {% if object.is_published %}
                    {{ object|title }}
                    {% else %}
                    <span class="text-muted">{{ object|title }}</span>
                    {% endif %}
                </p>
                <div class="mb-1 text-muted">{{ object.created_at }}</div>
                <p class="card-text mb-auto">{{ object.content }}</p>
                <div class="mb-1 text-muted">Просмотров: {{ object.count_views }}</div>
                <div class="button-group">
                    <a class="btn btn-link" href="{% url 'blogs:blogs_detail' object.pk %}" role="button">Открыть</a>
                    {% if perms.blogs.change_blogs %}
                    <a class="btn btn-link" href="{% url 'blogs:blogs_update' object.pk %}" role="button">Редактировать</a>
                    {% endif %}
                    {% if perms.blogs.delete_blogs %}
                    <a class="btn btn-link" href="{% url 'blogs:blogs_delete' object.pk %}" role="button">Удалить</a>
                    {% endif %}
                    {% if perms.blogs.can_publish %}
                    {% if object.is_published %}
                        <a href="{% url 'blogs:toggle_published' object.pk %}">Снять с публикации</a>
                    {% else %}
                        <a href="{% url 'blogs:toggle_published' object.pk %}">Опубликовать</a>
                    {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
</main>
{% endblock %}